DROP TABLE IF EXISTS stores;
DROP TABLE IF EXISTS opportunities;
CREATE TABLE stores (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, long NUMERIC NOT NULL, lat NUMERIC NOT NULL);
CREATE TABLE opportunities (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, product_name TEXT NOT NULL, quantity NUMERIC NOT NULL, is_available INTEGER NOT NULL, created_at STRING NOT NULL, store_id INTEGER NOT NULL, user_id TEXT);